-- Requisiciones -- nombre impreso y domicilio de cada unidad (encabezado DESTINO/DIRECCIÓN
-- del Excel de unidad). Salen de las hojas por unidad de los Excel oficiales por municipio;
-- antes el nombre se armaba como "C.S <nombre>" (mal para UMME/FAM) y no había domicilio.
alter table requi_unidades add column if not exists nombre_impresion text;
alter table requi_unidades add column if not exists direccion text;
update requi_unidades set nombre_impresion='C.S SANTA BÁRBARA', direccion='Luis Echeverria S/N, Santa Barbara, Corregidora.' where clues='QTSSA000830';
update requi_unidades set nombre_impresion='C.S LOS ÁNGELES', direccion='San Francisco S/N, Los Angeles, Corregidora.' where clues='QTSSA000842';
update requi_unidades set nombre_impresion='C.S JOAQUÍN HERRERA (LA CUEVA)', direccion=null where clues='QTSSA000854';
update requi_unidades set nombre_impresion='C.S LOS OLVERA', direccion='Sabino S/N, Los Olvera, Corregidora.' where clues='QTSSA000866';
update requi_unidades set nombre_impresion='C.S. SAN JOSÉ DE LOS OLVERA', direccion='Monterrey S/N, San José de los Olvera, Corregidora' where clues='QTSSA000883';
update requi_unidades set nombre_impresion='C.S PRESA DE BRAVO', direccion='Carretera a Coronero S/N, KM 13.5, Corregidora' where clues='QTSSA003640';
update requi_unidades set nombre_impresion='C.S LA NEGRETA', direccion='21 de Marzo S/N, La Negreta, Corregidora' where clues='QTSSA012252';
update requi_unidades set nombre_impresion='FAM CORREGIDORA', direccion=null where clues='QTSSA012532';
update requi_unidades set nombre_impresion='EMILIANO ZAPATA', direccion='Av. El Jacal S/N, Emiliano Zapata, Corregidora.' where clues='QTSSA012602';
update requi_unidades set nombre_impresion='C.S HUIMILPAN', direccion='Reforma N.587, Josefina Becerril, Huimilpan' where clues='QTSSA000953';
update requi_unidades set nombre_impresion='C.S APAPÁTARO', direccion='Boulevard Metropolitano km 10, Apapataro, Huimilpan.' where clues='QTSSA000970';
update requi_unidades set nombre_impresion='C.S CEJA DE BRAVO', direccion='Juan Pablo II #24, Ceja de Bravo, Huimilpan.' where clues='QTSSA000994';
update requi_unidades set nombre_impresion='C.S LOS CUES', direccion='Ignacio Zaragoza S/N, Los Cues, Huimilpan' where clues='QTSSA001006';
update requi_unidades set nombre_impresion='C.S LAGUNILLAS', direccion='Gomez Morín S/N, Lagunillas, Huimilpan.' where clues='QTSSA001011';
update requi_unidades set nombre_impresion='C.S EL MILAGRO', direccion='Belisario Dominguez Esquina Francisco Villa S/N, El Milagro, Huimilpan.' where clues='QTSSA001023';
update requi_unidades set nombre_impresion='C.S LA NORIA', direccion='Tequisquiapan Esquina Cadereyta S/N, La Noria, Huimilpan.' where clues='QTSSA001035';
update requi_unidades set nombre_impresion='C.S SAN PEDRO HUIMILPAN', direccion='31 de Enero S/N, San Pedro Huimilpan.' where clues='QTSSA001040';
update requi_unidades set nombre_impresion='UMME EL VEGIL', direccion=null where clues='QTSSA003535';
update requi_unidades set nombre_impresion='C.S BUENAVISTA', direccion='Carretera Buenavista, Taponas S/N, Buenavista. Huimilpan.' where clues='QTSSA003700';
update requi_unidades set nombre_impresion='UMME MÉDICO FARMACIA 2', direccion=null where clues='QTSSA012573';
update requi_unidades set nombre_impresion='C.S LA CAÑADA', direccion='Av. El Marques S/N, La Cañada, El Marques' where clues='QTSSA001315';
update requi_unidades set nombre_impresion='C.S AMAZCALA', direccion='Av. San Isidro S/N, Amazcala, El Marques' where clues='QTSSA001332';
update requi_unidades set nombre_impresion='C.S ATONGO', direccion='Calle San Francisco S/N, Atongo, El Marques' where clues='QTSSA001344';
update requi_unidades set nombre_impresion='C.S SAN MIGUEL LÁZARO CÁRDENAS', direccion='Calle Emiliano Zapata N.6, El Colorado, El Marques' where clues='QTSSA001356';
update requi_unidades set nombre_impresion='C.S LA GRIEGA', direccion='Emiliano Zapata S/N, La Griega, El Marques' where clues='QTSSA001390';
update requi_unidades set nombre_impresion='C.S JESÚS MARÍA', direccion='Av. Flores S/N, Jesús Maria, El Marques' where clues='QTSSA001402';
update requi_unidades set nombre_impresion='C.S PALO ALTO', direccion='Luareles, Esquina Robles S/N, Palo Alto, El Marques' where clues='QTSSA001426';
update requi_unidades set nombre_impresion='C.S EL PARAÍSO', direccion='Av. Paraiso S/N, El Paraiso, El Marques' where clues='QTSSA001431';
update requi_unidades set nombre_impresion='C.S SAN ISIDRO MIRANDA', direccion='Calle Nuevo León S/N, Miranda, El Marques' where clues='QTSSA001933';
update requi_unidades set nombre_impresion='C.S CHICHIMEQUILLAS', direccion='Calle Enrique Campos S/N, Chichimequillas, El Marques' where clues='QTSSA003571';
update requi_unidades set nombre_impresion='C.S NAVAJAS', direccion='Calle Sevilla S/N, Navajas, El Marques' where clues='QTSSA003580';
update requi_unidades set nombre_impresion='FAM CHICHIMEQUILLAS', direccion=null where clues='QTSSA012264';
update requi_unidades set nombre_impresion='C.S ALFAJAYUCAN', direccion='Calle S/N a un costado de la Ex-hacienda, Alfajayucan, El Marques' where clues='QTSSA012643';
update requi_unidades set nombre_impresion='C.S LA PIEDAD', direccion='Calle Dolores N.7, Villas La Piedad, La Piedas, El Marques' where clues='QTSSA012940';
update requi_unidades set nombre_impresion='UMME QUERÉTARO', direccion=null where clues='QTSSA001764';
update requi_unidades set nombre_impresion='C.S JURICA', direccion='Privada LiriosS/N, Pueblo de Jurica, Querétaro.' where clues='QTSSA001793';
update requi_unidades set nombre_impresion='C.S MENCHACA', direccion='Rio Lerma N.215, Menchaca, Querétaro.' where clues='QTSSA001810';
update requi_unidades set nombre_impresion='C.S SAN ANTONIO DE LA PUNTA', direccion='Hacienda La Gloria N.103, Las Tereas, San Antonio de la Punta, Querétaro.' where clues='QTSSA001822';
update requi_unidades set nombre_impresion='C.S SAN PABLO', direccion='Camino Real N.21, San Pablo, Querétaro.' where clues='QTSSA001834';
update requi_unidades set nombre_impresion='C.S FELIPE CARRILLO PUERTO', direccion='Plata S/N, El Progreso, Carrillo Puerto' where clues='QTSSA001846';
update requi_unidades set nombre_impresion='C.S LOMA BONITA', direccion='Creston N.232, Sátelite, Querétaro.' where clues='QTSSA001851';
update requi_unidades set nombre_impresion='C.S PEDRO ESCOBEDO', direccion='Nicolas Campa Esquina Pino Suarez S/N, Centro, Querétaro.' where clues='QTSSA001863';
update requi_unidades set nombre_impresion='C.S JOFRITO', direccion='Camino Real S/N, Jofrito, Querétaro.' where clues='QTSSA001904';
update requi_unidades set nombre_impresion='C.S MONTENEGRO', direccion='Independencia S/N, Montenegro, Querétaro.' where clues='QTSSA001916';
update requi_unidades set nombre_impresion='C.S PIE DE GALLO', direccion='Benito Juarez S/N, Pie de Gallo, Querétaro' where clues='QTSSA001921';
update requi_unidades set nombre_impresion='C.S SAN JOSÉ BUENAVISTA', direccion='Camino Real S/N, San José Buenavista, Querétaro.' where clues='QTSSA001945';
update requi_unidades set nombre_impresion='C.S SAN MIGUELITO', direccion='Hacienda la Solana S/N, San Miguelito,' where clues='QTSSA001962';
update requi_unidades set nombre_impresion='C.S SANTA MARÍA MAGDALENA', direccion='Epigmenio Gonzalez N.20,Santa Maria Magdalena,' where clues='QTSSA001974';
update requi_unidades set nombre_impresion='C.S LA SOLANA', direccion='Las Rosas S/N, La Solana, Querétaro.' where clues='QTSSA002003';
update requi_unidades set nombre_impresion='C.S TINAJA DE LA ESTANCIA', direccion=null where clues='QTSSA002015';
update requi_unidades set nombre_impresion='C.S LÁZARO CÁRDENAS', direccion='Carlos A. Madrazo N.3000, Lázaro Cardenas, Querétaro.' where clues='QTSSA002522';
update requi_unidades set nombre_impresion='C.S SAN PEDRITO PEÑUELAS', direccion='Pie de la Cuesta N.2253, Lomas de San Pedrito P, SPP, Querétaro.' where clues='QTSSA002534';
update requi_unidades set nombre_impresion='C.S MENCHACA NORTE', direccion='Cerro del Peñon S/N Esquina 18 de Julio, Colinas de Menchaca, Menchaca' where clues='QTSSA002703';
update requi_unidades set nombre_impresion='UMME CERRO DE LA CRUZ', direccion=null where clues='QTSSA003553';
update requi_unidades set nombre_impresion='UMME LA LUZ', direccion=null where clues='QTSSA003562';
update requi_unidades set nombre_impresion='UMME SAN PEDRITO EL OBRAJE', direccion=null where clues='QTSSA003595';
update requi_unidades set nombre_impresion='UMME RANCHO LARGO', direccion=null where clues='QTSSA003604';
update requi_unidades set nombre_impresion='C.S LA GOTERA', direccion='Juventino Castro S/N, La Gotera, Querétaro.' where clues='QTSSA003715';
update requi_unidades set nombre_impresion='C.S SAN JOSÉ EL ALTO', direccion='Campeche S/N, San José el Alto, Querétaro.' where clues='QTSSA012240';
update requi_unidades set nombre_impresion='FAM SAN JOSÉ BUENAVISTA', direccion=null where clues='QTSSA012276';
update requi_unidades set nombre_impresion='FAM PEDRO ESCOBEDO', direccion=null where clues='QTSSA012281';
update requi_unidades set nombre_impresion='FAM MARQUÉS 2 (PALO ALTO)', direccion=null where clues='QTSSA012544';
update requi_unidades set nombre_impresion='UMME MÉDICO FARMACIA 1', direccion=null where clues='QTSSA012556';
update requi_unidades set nombre_impresion='UMME AMBULANCIA 1', direccion=null where clues='QTSSA012561';
update requi_unidades set nombre_impresion='UMME MÉDICO DENTAL', direccion=null where clues='QTSSA012631';
update requi_unidades set nombre_impresion='C.S. SANTA ROSA JAUREGUI', direccion='Rio Bravo S/N, Rivera Mexicana, SRJ, Querétaro.' where clues='QTSSA012655';
update requi_unidades set nombre_impresion='C.S SATÉLITE', direccion='Cordillera Himalaya S/N, Colinas del poniente, Satélite, Querétaro' where clues='QTSSA012923';
update requi_unidades set nombre_impresion='C.S. SAN PEDRO MÁRTIR', direccion='Hidalgo S/N, San Pedro Martir, Querétaro.' where clues='QTSSA012976';
update requi_unidades set nombre_impresion='C.S LOMAS DE CASABLANCA', direccion='Abraham Catellanos S/N, Reforma Agraria, Querétaro' where clues='QTSSA012982';
update requi_unidades set nombre_impresion='C.S TLACOTE EL BAJO', direccion='Miguel Hidalgo N.327, Tlacote, Querétaro.' where clues='QTSSA013034';
